services:
  blogdb:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
    #ports:
    #  - '54321:5432'
    volumes:
      - ../init_blogdb.sql:/docker-entrypoint-initdb.d/init_blogdb.sql

  server:
    build: 
        context: ../.
    ports:
      - "8081:8081"
    environment:
        HTTP_PORT: :8081
        JWT_SECRET: JWT_SECRET
        DATABASE_URL: postgres://user:password@blogdb/blog
    depends_on:
      - blogdb

